 
---
# tasks file for nginx_role

- name: Install Nginx
  package:
    name: nginx
    state: present

- name: Deploy custom Nginx configuration
  template:
    src: nginx.conf.j2
    dest: /etc/nginx/nginx.conf
  notify: reload nginx

- name: Deploy website content
  copy:
    src: index.html
    dest: /usr/share/nginx/html/index.html

- name: Ensure Nginx is running and enabled
  service:
    name: nginx
    state: started
    enabled: yes
